version: '3'
services:
  node-app:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: app
    networks:
      - backend
    ports:
      - 8008:8080
    command: bash -c /usr/src/app/start.sh
    env_file: .env
    links:
      - mysql-database
      - phpmyadmin
  mysql-database:
    image: 'mysql:5.7'
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - '6033:3306'
    networks:
      - backend
    volumes:
      - 'db-data:/var/lib/mysql'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    networks:
      - backend
    links:
      - mysql-database
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: on-failure
    ports:
      - '8081:80'
volumes:
  db-data: null

networks:
  backend:
